- repo: https://github.com/ansible/ansible-lint.git
  sha: v4.2.0
  hooks:
    - id: ansible-lint
      files: ^(?!\.).*\.(yaml|yml)$

- repo: https://github.com/willthames/ansible-review
  sha: v0.13.9
  hooks:
    - id: ansible-review
