---

- name: Install Apache.
  yum:
    name:
      - httpd
      - mod_wsgi
    state: present

- name: Start Apache.
  service:
    name: httpd
    enabled: yes
    state: started

- name: Set SELinux permissions to allow Apache to access pgadmin sqlite db.
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes

- name: Set SELinux permissions to allow Apache to email password resets.
  seboolean:
    name: httpd_can_sendmail
    state: yes
    persistent: yes

- name: Add PostgreSQL repo.
  yum:
    name: "{{ pgdg_package }}"
    state: present

- name: Install python dependency packages.
  yum:
    name:
      - python-flask
      - python-psycopg2
    state: present

- name: Install python pip modules.
  pip:
    name: flask-compress
    state: present

- name: Install pgAdmin4-web.
  yum:
    name: pgadmin4-web
    state: present

- name: Install client packages.
  yum:
    name: postgresql10
    state: present

- name: Initialize pgAdmin4.
  command: python /usr/lib/python2.7/site-packages/pgadmin4-web/setup.py
  args:
    creates: /var/lib/pgadmin/pgadmin4.db
  environment:
    PGADMIN_SETUP_EMAIL: "{{ pgadmin_setup_email }}"
    PGADMIN_SETUP_PASSWORD: "{{ pgadmin_setup_password }}"

- name: Install pgAdmin4 site config.
  copy:
    src: /etc/httpd/conf.d/pgadmin4.conf.sample
    dest: /etc/httpd/conf.d/pgadmin4.conf
    remote_src: yes
  notify: restart httpd

- name: Fix pgAdmin permissions.
  file:
    path: "{{ item }}"
    setype: httpd_sys_rw_content_t
    owner: apache
    group: apache
    recurse: yes
  with_items:
  - /var/log/pgadmin
  - /var/lib/pgadmin
