---

- name: Install SELinux libsemanage-python support.
  yum:
    name:
      - libsemanage-python
    state: present

- name: Install Apache.
  yum:
    name:
      - httpd
      - mod_wsgi
    state: present

- name: Start Apache.
  service:
    name: httpd
    enabled: yes
    state: started

- block:
  - name: Set SELinux permissions to allow Apache to access pgadmin sqlite db.
    seboolean:
      name: httpd_can_network_connect_db
      state: yes
      persistent: yes

  - name: Set SELinux permissions to allow Apache to use LDAP authentication.
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes

  - name: Set SELinux permissions to allow Apache to email password resets.
    seboolean:
      name: httpd_can_sendmail
      state: yes
      persistent: yes

  when:
    - ansible_selinux is defined
    - ansible_selinux
    - ansible_selinux.status == 'enabled'

- name: Add PostgreSQL repo.
  yum:
    name: "{{ pgdg_package }}"
    state: present

- name: Add pgAdmin4 repo.
  yum:
    name: "{{ pgadmin_package }}"
    state: present

- name: Install python dependency packages.
  yum:
    name:
      - python-alembic
      - python-flask
      - python-psycopg2
    state: present

- name: Install python pip modules.
  pip:
    name:
      - bcrypt<=3.1.7
      - blinker
      - click
      - pexpect>=3.3
      - flask_babelex
      - flask-compress
      - Flask-Security-Too>=3.0.0
      - future
      - ldap3
      - passlib
      - python-dateutil>=2.8.0
      - pytz
      - simplejson
      - speaklater
      - six>=1.12.0
      - sshtunnel>=0.1.5
      - SQLAlchemy>=1.3.13
      - sqlparse
      - Werkzeug>=0.15.0
      - WTForms
    state: present
  notify: restart httpd

- name: Install pgAdmin4-web.
  yum:
    name: pgadmin4-web
    update_cache: yes
    state: present

- name: Install client packages.
  yum:
    name: postgresql12
    state: present

- name: Locate the setup shell script.
  find:
    paths: /usr/pgadmin4
    patterns: setup-web.sh
    file_type: file
    recurse: yes
  register: shell_setup_path

- name: Show location of setup-web.sh.
  debug:
    var: shell_setup_path

- name: Locate the setup python script.
  find:
    paths: /opt
    patterns: pgadmin4-web
    file_type: directory
    recurse: yes
  register: python_setup_path

- name: Show location of pgadmin4-web directory.
  debug:
    var: python_setup_path

- name: Initialize pgAdmin4.
  expect:
    command: "python {{ python_setup_path.files[0].path }}/setup.py"
    creates: /var/lib/pgadmin/pgadmin4.db
    echo: yes
    responses:
      'Email\ address:': "{{ pgadmin_setup_email | trim }}"
      'Password:': "{{ pgadmin_setup_password | trim }}"
      'Retype\ password:': "{{ pgadmin_setup_password | trim }}"
      'Do\ you\ wish\ to\ continue\ \(y/n\)\?': "y"
      'Would\ you\ like\ to\ continue\ \(y/n\)\?': "y"
#  no_log: true

- name: Install pgAdmin4 site config.
  copy:
    src: /etc/httpd/conf.d/pgadmin4.conf.sample
    dest: /etc/httpd/conf.d/pgadmin4.conf
    remote_src: yes
    mode: 0644
  notify: restart httpd

- name: "Fix pgAdmin permissions."  # noqa 208
  file:
    path: "{{ item }}"
    setype: httpd_sys_rw_content_t
    owner: apache
    group: apache
    recurse: yes
  with_items:
    - /var/log/pgadmin
    - /var/lib/pgadmin
