---

- name: Install SELinux libsemanage-python support.
  yum:
    name:
      - libsemanage-python
    state: present

- name: Install Apache.
  yum:
    name:
      - httpd
      - mod_wsgi
    state: present

- name: Start Apache.
  service:
    name: httpd
    enabled: yes
    state: started

- block:
  - name: Set SELinux permissions to allow Apache to access pgadmin sqlite db.
    seboolean:
      name: httpd_can_network_connect_db
      state: yes
      persistent: yes

  - name: Set SELinux permissions to allow Apache to use LDAP authentication.
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes

  - name: Set SELinux permissions to allow Apache to email password resets.
    seboolean:
      name: httpd_can_sendmail
      state: yes
      persistent: yes

  when:
    - ansible_selinux is defined
    - ansible_selinux
    - ansible_selinux.status == 'enabled'

- name: Add PostgreSQL repo.
  yum:
    name: "{{ pgdg_package }}"
    state: present

- name: Add pgAdmin4 repo.
  yum:
    name: "{{ pgadmin_package }}"
    state: present

- name: Install python dependency packages.
  yum:
    name:
      - python3
      - python3-pip
      - python3-psycopg2
      - python36-bcrypt
      - python36-click
      - python36-pexpect
      - python36-future
      - python36-ldap3
      - python36-pytz
      - python36-simplejson
      - python36-six
      - python36-werkzeug
    state: present

- name: Install python pip modules.
  pip:
    name:
      - alembic
      - blinker
      - Flask
      - flask_babelex
      - flask-compress
      - Flask-Security-Too>=3.0.0
      - flask-socketio
      - passlib
      - python-dateutil>=2.8.0
      - speaklater
      - sshtunnel>=0.1.5
      - SQLAlchemy>=1.3.13
      - sqlparse
      - WTForms
    executable: pip3
    state: present
  notify: restart httpd

- name: Install pgAdmin4-web.
  yum:
    name: pgadmin4-web
    update_cache: yes
    state: present

- name: Install client packages.
  yum:
    name: postgresql12
    state: present

- name: Locate the setup python script.
  find:
    paths: /usr/pgadmin4
    patterns: setup.py
    file_type: file
    recurse: yes
  register: python_setup_path

- name: Show location of pgadmin4 directory.
  debug:
    var: python_setup_path

- name: Initialize pgAdmin4.
  expect:
    command: "python3 {{ python_setup_path.files[0].path }}"
    creates: /var/lib/pgadmin/pgadmin4.db
    echo: yes
    responses:
      'Email\ address:': "{{ pgadmin_setup_email | trim }}"
      'Password:': "{{ pgadmin_setup_password | trim }}"
      'Retype\ password:': "{{ pgadmin_setup_password | trim }}"
      'Do\ you\ wish\ to\ continue\ \(y/n\)\?': "y"
      'Would\ you\ like\ to\ continue\ \(y/n\)\?': "y"
#  no_log: true

- name: Install pgAdmin4 site config.
  copy:
    src: /etc/httpd/conf.d/pgadmin4.conf.sample
    dest: /etc/httpd/conf.d/pgadmin4.conf
    remote_src: yes
    mode: 0644
  notify: restart httpd

- name: "Fix pgAdmin permissions."  # noqa 208
  file:
    path: "{{ item }}"
    setype: httpd_sys_rw_content_t
    owner: apache
    group: apache
    recurse: yes
  with_items:
    - /var/log/pgadmin
    - /var/lib/pgadmin
