---

- name: Install Apache.
  yum:
    name:
      - httpd
      - mod_wsgi
    state: present

- name: Start Apache.
  service:
    name: httpd
    enabled: yes
    state: started

- name: Set SELinux permissions to allow Apache to access pgadmin sqlite db.
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes
  when:
    - ansible_selinux is defined
    - ansible_selinux.status == 'enabled'

- name: Set SELinux permissions to allow Apache to email password resets.
  seboolean:
    name: httpd_can_sendmail
    state: yes
    persistent: yes
  when:
    - ansible_selinux is defined
    - ansible_selinux.status == 'enabled'

- name: Add PostgreSQL repo.
  yum:
    name: "{{ pgdg_package }}"
    state: present

- name: Install python dependency packages.
  yum:
    name:
      - python-alembic
      - python-flask
      - python-psycopg2
    state: present

- name: Install python pip modules.
  pip:
    name:
      - flask_babelex
      - flask-compress
      - ldap3
    state: present
  notify: restart httpd

- name: Install pgAdmin4-web.
  yum:
    name: pgadmin4-web
    state: present

- name: Install client packages.
  yum:
    name: postgresql11
    state: present

- name: Locate the setup script.
  find:
    paths: /usr/lib
    patterns: 'setup.py'
    file_type: file
    recurse: yes
  register: setup_path

- debug:
    var: setup_path

- name: Initialize pgAdmin4.
  command: python /usr/lib/python2.7/site-packages/pgadmin4-web/setup.py
  args:
    creates: /var/lib/pgadmin/pgadmin4.db
  environment:
    PGADMIN_SETUP_EMAIL: "{{ pgadmin_setup_email }}"
    PGADMIN_SETUP_PASSWORD: "{{ pgadmin_setup_password }}"

- name: Install pgAdmin4 site config.
  copy:
    src: /etc/httpd/conf.d/pgadmin4.conf.sample
    dest: /etc/httpd/conf.d/pgadmin4.conf
    remote_src: yes
    mode: 0644
  notify: restart httpd

- name: "Fix pgAdmin permissions." # noqa 208
  file:
    path: "{{ item }}"
    setype: httpd_sys_rw_content_t
    owner: apache
    group: apache
    recurse: yes
  with_items:
    - /var/log/pgadmin
    - /var/lib/pgadmin
